// ActionCreator Types
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const INDIVIDUAL_USER_POSTS = "INDIVIDUAL_USER_POSTS";
export const INDIVIDUAL_USER_POSTS_ERROR = "INDIVIDUAL_USER_POSTS_ERROR";
export const IS_LOADING_POSTS = "IS_LOADING_POSTS";
