// ActionCreator Types
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_STATE = "REGISTRATION_STATE";
export const RESET_STATE = "RESET_STATE";
