// ActionCreator Types
// export const AUTH_STATE = "AUTH_STATE";
// export const SET_TOKEN = "SET_TOKEN";
// export const RESET_STATE = "RESET_STATE";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const DP_UPDATION_SUCCESS = "DP_UPDATION_SUCCESS";
export const DP_UPDATION_ERROR = "DP_UPDATION_ERROR";
export const IS_LOADING_POSTS = "IS_LOADING_POSTS";
export const FETCHIG_PROFILE_USER_DETAILS_SUCCESS =
  "FETCHIG_PROFILE_USER_DETAILS_SUCCESS";
export const FETCHIG_PROFILE_USER_DETAILS_ERROR =
  "FETCHIG_PROFILE_USER_DETAILS_ERROR";
export const EMPTY_PROFILE_USER_POSTS = "EMPTY_PROFILE_USER_POSTS";
export const FRIENDSHIP_ACTION_SUCCESS = "FRIENDSHIP_ACTION_SUCCESS";
export const FRIENDSHIP_ACTION_ERROR = "FRIENDSHIP_ACTION_ERROR";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const REMOVE_TOKEN = "REMOVE_TOKEN";
