// ActionCreator Types
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const FETCHED_POSTS = "FETCHED_POSTS";
export const POSTS_FETCHING_ERROR = "POSTS_FETCHING_ERROR";
export const REACTION_UPSERTION_SUCCESS = "REACTION_UPSERTION_SUCCESS";
export const REACTION_UPSERTION_ERROR = "REACTION_UPSERTION_ERROR";
export const COMMENT_UPSERTION_SUCCESS = "COMMENT_UPSERTION_SUCCESS";
export const COMMENT_UPSERTION_ERROR = "COMMENT_UPSERTION_ERROR";
export const POST_DELETION_SUCCESS = "POST_DELETION_SUCCESS";
export const POST_DELETION_ERROR = "POST_DELETION_ERROR";
export const ASSIGN_PROFILE_USER_POSTS = "ASSIGN_PROFILE_USER_POSTS";
